---
- name: Download yay
  hosts: localhost
  connection: local
  become: yes
  vars_files:
  - ../data.txt
  tasks:
  - name: Download YaY
    shell: git clone https://aur.archlinux.org/yay-git.git /opt/yay-git  
- name: Change owner yay folder
  hosts: localhost
  connection: local
  become: yes
  vars_files:
  - ../data.txt
  tasks:  
  - name: Change user owner
    shell: chown -R {{ host_username }}:{{ host_username }} /opt/yay-git
- name: Install yay
  hosts: localhost
  connection: local
  become: yes
  become_user: "{{ host_username }}"
  vars_files:
  - ../data.txt
  tasks:
  - name: Compile YaY
    shell: cd /opt/yay-git && makepkg -si --noconfirm 
  
