---
- name: Start and enable services
  hosts: localhost
  connection: local
  tasks:
  - name: Start and enable ssh
    systemd:
        name: sshd
        enabled: yes
        scope: user
        state: started
